httpsec: externalize ClientIP()
DataDog/appsec-internal-go pull request #5
Opened 2023-03-29 22:02 UTC by Julio-Guerra

Externalise dd-trace-go's `httpsec.ClientIP()` in this repo to be able to reuse it in the agent. To do so:
1. Copy/Paste the original implementation.
2. Let dd-trace-go configure the function by always passing the list of HTTP headers to monitor.
3. Found a mistake fixed with multiple headers where the `break` statement was breaking the inner loop rather than the main one. This was preventing stopping the header's loop as soon as a global IP was found.

2023-04-04 15:00 UTC, Hellzy reviewed
I feel like this code has become cleaner over time, it's nice to see 😃
Couple comments on my side.

2023-04-05 09:49 UTC, Julio-Guerra commented on httpsec/client_ip_test.go
> +	//}
Restored in [4e9b83a](https://github.com/DataDog/appsec-internal-go/pull/5/commits/4e9b83a93282aae408e47fd27f8bf996eefb0e0a)

2023-04-05 09:49 UTC, Julio-Guerra commented on httpsec/client_ip.go
> +func ClientIP(hdrs map[string][]string, hasCanonicalMIMEHeaderKeys bool, remoteAddr string, monitoredHeaders []string) (remoteIP, clientIP netip.Addr) {
Renamed in [d1d43fb](https://github.com/DataDog/appsec-internal-go/pull/5/commits/d1d43fb0cf134223967c685700e49532fc867674)

2023-04-05 11:30 UTC, Hellzy requested changes

2023-04-05 11:30 UTC, Hellzy commented on httpsec/client_ip.go
> +		tags["network.client.ip"] = remoteIP.String()
We should probably use `RemoteIPTag` here
```suggestion
		tags[RemoteIPTag] = remoteIP.String()
```

2023-04-05 11:30 UTC, Hellzy commented on httpsec/client_ip.go
> +		tags["http.client_ip"] = clientIP.String()
Same with `ClientIPTag`
```suggestion
		tags[ClientIPTag] = clientIP.String()
```

2023-04-05 12:48 UTC, Hellzy approved these changes

2023-04-05 12:48 UTC, merged